# Example Configuration File for DCAM
general:
  year: 2022
  month: 12
  day: 22
  outputDir: # If user wants to output result files to an external drive, otherwise save to current output directory
  duration: 30
  monteCarloRuns: 1
aircraft:
  frequency: 400 # [Hz]
  waypoints: SCurveFlightPath
  lookaheadDistance: 50 # [m]
  noisePowerForces: [250 250 250]
  noiseTSForces: 0.1
  initialState:
    u: 75 # [m/s]
    v: 0 # [m/s]
    w: 0 # [m/s]
    p: 0 # [rad/s]
    q: 0 # [rad/s]
    r: 0 # [rad/s]
    x: 0 # [m]
    y: 0 # [m]
    z: -1000 # [m]
    phi: 0 # [rad]
    theta: 4*pi/180 # [rad]
    psi: pi # [rad]
    clkBias: 0
    clkDrift: 0
