# Example Configuration File for DCAM
general:
  year: 2022
  month: 12
  day: 22
  outputDir: # If user wants to output result files to an external drive, otherwise save to current output directory
  duration: 60
  monteCarloRuns: 100
aircraft:
  frequency: 200 # [Hz]
  waypoints: SCurveFlightPath
  lookaheadDistance: 50 # [m]
  noiseVariance: [0;0;0;0;0;0;1e-14;1e-14;0;pi/1000;pi/1000;pi/1000]
  clockType: OCXO # [LOW-TCXO;HIGH-TXCO;OCXO;RUBIDIUM;CESIUM]
  initialState:
    u: 75 # [m/s]
    v: 0 # [m/s]
    w: 0 # [m/s]
    p: 0 # [rad/s]
    q: 0 # [rad/s]
    r: 0 # [rad/s]
    lat: 0.65617 # [radians]
    long: -2.1376 # [radians]
    alt: 500 # [m]
    phi: '0*pi/180' # [rad]
    theta: 4*pi/180 # [rad]
    psi: '0' # [rad]
    clkBias: 0
    clkDrift: 0
signal:
  CN0: 15
  amplitude: 1
